### ISSUE TITLE
failing TODO test $log->contains_ok not ignored when it should

### ISSUE THREAD

**Issue by ebaudrez** [dagolden/Log-Any#12]
As the test script below shows, a failing TODO test $log->contains_ok() is not ignored when it should. Below script tests fine with Log::Any 0.15, fails with Log::Any 1.00 and 1.03 (and presumably everything in between) with output

    example.t .. 
    not ok 1 - log contains '(?^:should not be there)'
    1..1
    
    #   Failed test 'log contains '(?^:should not be there)''
    #   at /home/ebaudrez/opt/perl/5.18.1/lib/site_perl/5.18.1/Log/Any/Proxy/Test.pm line 26.
    # could not find message matching (?^:should not be there); log contains: bless( {category => 'main'}, 'Log::Any::Adapter::Test' )
    # Looks like you failed 1 test of 1.
    Dubious, test returned 1 (wstat 256, 0x100)
    Failed 1/1 subtests 
    
    Test Summary Report
    -------------------
    example.t (Wstat: 256 Tests: 1 Failed: 1)
      Failed test:  1
      Non-zero exit status: 1
    Files=1, Tests=1,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.03 cusr  0.00 csys =  0.05 CPU)
    Result: FAIL

the test script example.t:

    use strict;
    use warnings;
    use Test::More;
    use Log::Any::Test;
    use Log::Any '$log';
    
    TODO: {
        local $TODO = 'to do';
        $log->contains_ok(qr/should not be there/);
    }       
    
    done_testing;

I have not tested with other methods yet. Do get in touch if you need more information, I will gladly provide it.

**Comment by dagolden** [comment]
Thanks for the report. I'll check it out.
