### ISSUE TITLE
Using make_method on Log::Any::Proxy after upgrade from v0.15

### ISSUE THREAD

**Issue by mjemmeson** [dagolden/Log-Any#13]
Hi,

We are using "Log::Any::Utils::make_method" to add in missing log methods that an app requires to existing adapters. Previously had been adding them to the Log::Any::Adapter::* classes. After an upgrade from v0.15 to v1.03 it looks like we have to add them to Log::Any::Proxy.

Please can you confirm that this is correct, or if not what we should be doing?

thanks,
Michael

**Comment by dagolden** [comment]
If could me more or give me some code examples, I might be able to give you better advice.

Without that information, my best guess is that it sounds like you should write a subclass of Log::Any::Proxy and add your methods to that.

There's a currently undocumented feature to tell Log::Any what proxy class to use:

```
use Log::Any '$log', proxy_class => "My::Log::Proxy";
```

David

**Comment by mjemmeson** [comment]
Thanks for the reply. Subclassing Log::Any::Proxy sounds like a good option, since it's the app which is needing the extra methods, rather than an adapter not supporting them (so we're adding them whatever adapter is loaded).

The code is a Mojolicious Plugin and something like:

    use Log::Any qw( $log );

    sub register {
        my ($self, $app ) = @_;
        my $logger = 'Log4perl'; # or "Stderr" etc
 
       Log::Any::Adapter->set($logger);

        # adding in extra methods that Mojo::Log has (and Mojolicious uses)
        Log::Any::Adapter::Util::make_method(
            'log',
            sub { shift->info(@_) },
            'Log::Any::Adapter::' . $logger,
        );
        Log::Any::Adapter::Util::make_method(
            'history',
            sub { [] },
            'Log::Any::Adapter::' . $logger,
        );

        $app->log( $log );
    }

The aim is that the Mojolicious controllers, plugins, etc can still call `$app->log->debug()` etc to log, whilst other modules (like models) not part of the app can `use Log::Any qw( $log )` to access the same logger.

Michael

**Comment by xdg** [comment]
As there's been no feedback and the proposed solution sounds like it will work, I'm closing this issue.
