### ISSUE TITLE
Log::Any::Adapter::File option to open files as utf8

### ISSUE THREAD

**Issue by brainbuz** [dagolden/Log-Any#23]
Log::Any::Adapter::File uses the default encoding with no option to specify a binmode. To demonstrate this and a fix I did the following.

$self->log->debug( "utf8 has defined many star symbols: \N{WHITE STAR} \N{BLACK STAR}" ); 

In your log see something like â˜† â˜ in your entry.

Modify Log::Any::Adapter::File around line 38: (add binmode to >>).

open( $self->{fh}, ">>:utf8", $file )
      or die "cannot open '$file' for append: $!";

See the stars in your log entry!! 

It should be easy to set binmode through an argument, but I did not comprehend Log::Any::Adapter::File's object creation process well enough to quickly complete this myself.

**Comment by dagolden** [comment]
Great catch!  It should definitely take an argument -- or even just default to UTF-8 without an argument.  Same goes for Stdout and Stderr, too.

I'm about to go on vacation, but hope to address this in a few weeks after I get back and dig out.  :-)
