### ISSUE TITLE
Significant increase in startup overhead compared to 0.15

### ISSUE THREAD

**Issue by perlancar** [dagolden/Log-Any#24]
Hi David,

Log::Any 0.15 is quite minimal so I don't have much reservations in loading it in my modules. 'use Log::Any;' statement loads only 2 files Log/Any.pm and Log/Any/Adapter/Null.pm for a total of 416 lines and load time of under 1ms.

Log::Any 1.00 now significantly increases this overhead to 10 files, including Data::Dumper and friends, for a total of 4489 lines and about 6-10ms of loading time.

I know this is not much in most cases, but it's a major regression and now this makes me have to think twice when loading Log::Any in some cases. Which is rather unfortunate as I view Log::Any to be quite universal.

**Comment by dagolden** [comment]
Interesting. I'll see how much of that loading can be made lazy.
