### ISSUE TITLE
where has Log::Any::Adapter::Test::Memory gone?

### ISSUE THREAD

**Issue by abraxxa** [dagolden/Log-Any#27]
Message::Passing::Output::Log::Any::Adapter has started failing because of it missing: http://matrix.cpantesters.org/?dist=Message-Passing-Output-Log-Any-Adapter+0.002

I searched the repo and found it mentioned in https://github.com/dagolden/Log-Any/commit/9d1ee8cc6ac4b8891d79cf6e763d89727ece1f02#diff-a580a87ff9da14b51504d149be8ecaffR16 but the file seems to have been missing at that time already: https://github.com/dagolden/Log-Any/tree/9d1ee8cc6ac4b8891d79cf6e763d89727ece1f02/lib/Log/Any/Adapter

**Comment by xdg** [comment]
This has been fixed in Message::Passing::Output::Log::Any::Adapter
