### ISSUE TITLE
About configuring proxy object as argument to Log::Any

### ISSUE THREAD

**Issue by perlancar** [dagolden/Log-Any#29]
I understand the rationale of proxy object. But I have reservations about setting/configuring it as argument to Log::Any. I think it should be global.

Log::Any is usually used by module authors for producing logs by adding something like:

    use Log::Any '$log';

it should be as simple as possible, without configuring any proxy object. And the statement should not change whenever a module user wants to format/customize log messages diferently.

In addition, I think proxy object should be created/used only right before being passed to adapters (log consumers), and should preferrably be skip(pable) in the case of default Null adapter (which essentially means that "there is no log consumer").

**Comment by xdg** [comment]
Configuration isn't necessary, but it allows log producers to easily hook into the process instead of having to wrap all calls to the logger with their own customization code.
