### ISSUE TITLE
Invalid example in SYNOPSIS for Moo

### ISSUE THREAD

**Issue by ymyasoedov** [dagolden/Log-Any#32]
The following example in SYNOPSIS is invalid:

```perl
package Foo;
use Moo;

has log => (
    is => 'ro',
    isa => 'Log::Any::Proxy',
    default => sub { Log::Any->get_logger },
);
```

Because of **isa** in Moo takes a coderef which is used to validate the attribute (see documentation for Moo). If you try to compile a code from that example, you'll get something like this:

```
$ perl foo.pl 
Invalid isa 'Log::Any::Proxy' for Foo->log not a coderef or code-convertible object at /usr/lib/perl5/site_perl/5.20.1/Method/Generate/Accessor.pm line 663.
```

In other words, when you use Moo you don't need **isa** at all:

```perl
package Foo;
use Moo;

has log => (
    is => 'ro',
    default => sub { Log::Any->get_logger },
);
```

**Comment by abraxxa** [comment]
I'll add my findings to this issue:
```use Log::Any;```
or maybe
```use Log::Any qw();```
is missing as well.
