### ISSUE TITLE
Incorrectly adds spaces when given a list

### ISSUE THREAD

**Issue by nigelhorne** [dagolden/Log-Any#33]
This program:

    use Log::Any::Adapter;
    Log::Any::Adapter->set('Stdout');

    my $logger = Log::Any->get_logger(category => 'foo');

    $logger->debug('a', 'b', 'c');

Prints "a b c"; 

It should not add spaces - Log::log4perl doesn't in a similar scenario.

**Comment by xdg** [comment]
Some logging packages join with spaces, and some don't, so whatever I choose, someone will be unhappy.  I decided to have Log::Any join with spaces, as an extra space is easier to read/parse than a missing space.  You could join them yourself before logging or you could apply a `filter` that squashes spaces:
```
sub { local $_ = pop; tr[ ][ ]s; $_ }
```
